# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\PYTHON\prg.ui',
# licensing of 'C:\PYTHON\prg.ui' applies.
#
# Created: Tue Aug 27 15:04:25 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(282, 465)
        Dialog.setStyleSheet("QPushButton{\n"
"    font-size:50px;\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:silver;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:black;\n"
"    color:white;\n"
"}\n"
"QLineEdit{\n"
"    font-size:50px;\n"
"    text-aline:center;\n"
"    border:none;\n"
"}\n"
"QLabel{\n"
"    font-size:20px;\n"
"}\n"
"QWidget{\n"
"    border:#4B5FF4;\n"
"}")
        self.game = QtWidgets.QTabWidget(Dialog)
        self.game.setGeometry(QtCore.QRect(0, 0, 281, 401))
        self.game.setDocumentMode(False)
        self.game.setTabsClosable(False)
        self.game.setMovable(False)
        self.game.setObjectName("game")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 260, 91, 81))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(30, 260, 91, 81))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    font-size:50px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(-10, 40, 291, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 60, 51, 71))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(40, 60, 51, 71))
        self.lineEdit.setObjectName("lineEdit")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(-10, 130, 291, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(10, 180, 271, 31))
        self.label_6.setStyleSheet("font-size:18px;")
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(20, 150, 241, 31))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 121, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(150, 10, 121, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(20, 200, 251, 41))
        self.label_12.setObjectName("label_12")
        self.game.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 260, 91, 81))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_4.setGeometry(QtCore.QRect(150, 260, 91, 81))
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 60, 51, 71))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_4.setGeometry(QtCore.QRect(190, 60, 51, 71))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.line_3 = QtWidgets.QFrame(self.tab_3)
        self.line_3.setGeometry(QtCore.QRect(0, 30, 281, 41))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_5.setGeometry(QtCore.QRect(110, 60, 51, 71))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.line_4 = QtWidgets.QFrame(self.tab_3)
        self.line_4.setGeometry(QtCore.QRect(0, 130, 281, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(20, 160, 241, 31))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(10, 190, 271, 31))
        self.label_14.setStyleSheet("font-size:18px;")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(20, 220, 251, 41))
        self.label_15.setObjectName("label_15")
        self.label_19 = QtWidgets.QLabel(self.tab_3)
        self.label_19.setGeometry(QtCore.QRect(10, 10, 131, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tab_3)
        self.label_20.setGeometry(QtCore.QRect(150, 10, 121, 21))
        self.label_20.setObjectName("label_20")
        self.game.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.line_5 = QtWidgets.QFrame(self.tab_4)
        self.line_5.setGeometry(QtCore.QRect(0, 40, 281, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.tab_4)
        self.line_6.setGeometry(QtCore.QRect(0, 130, 281, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_6.setGeometry(QtCore.QRect(30, 60, 51, 71))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_7.setGeometry(QtCore.QRect(110, 60, 51, 71))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_8.setGeometry(QtCore.QRect(190, 60, 51, 71))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 260, 91, 81))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_6.setGeometry(QtCore.QRect(180, 260, 91, 81))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_7.setGeometry(QtCore.QRect(90, 260, 91, 81))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_16 = QtWidgets.QLabel(self.tab_4)
        self.label_16.setGeometry(QtCore.QRect(20, 160, 241, 31))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab_4)
        self.label_17.setGeometry(QtCore.QRect(0, 200, 291, 31))
        self.label_17.setStyleSheet("font-size:17px;")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab_4)
        self.label_18.setGeometry(QtCore.QRect(10, 230, 251, 31))
        self.label_18.setObjectName("label_18")
        self.label_21 = QtWidgets.QLabel(self.tab_4)
        self.label_21.setGeometry(QtCore.QRect(150, 10, 121, 21))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tab_4)
        self.label_22.setGeometry(QtCore.QRect(10, 10, 131, 16))
        self.label_22.setObjectName("label_22")
        self.game.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 81, 24))
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_9.setGeometry(QtCore.QRect(60, 60, 181, 21))
        self.lineEdit_9.setStyleSheet("font-size:17px;")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(0, 200, 141, 24))
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.spinBox = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox.setGeometry(QtCore.QRect(150, 200, 101, 31))
        self.spinBox.setStyleSheet("font-size:19px;")
        self.spinBox.setMinimum(2500)
        self.spinBox.setMaximum(1000000)
        self.spinBox.setSingleStep(250)
        self.spinBox.setObjectName("spinBox")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(260, 200, 21, 21))
        self.label_5.setObjectName("label_5")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_9.setGeometry(QtCore.QRect(80, 100, 101, 23))
        self.pushButton_9.setStyleSheet("font-size:18px;")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_10.setGeometry(QtCore.QRect(80, 250, 101, 23))
        self.pushButton_10.setStyleSheet("font-size:18px;")
        self.pushButton_10.setObjectName("pushButton_10")
        self.game.addTab(self.tab_2, "")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(30, 415, 221, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(100, 410, 111, 31))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.pushButton_8 = QtWidgets.QPushButton(Dialog)
        self.pushButton_8.setGeometry(QtCore.QRect(210, 410, 71, 41))
        self.pushButton_8.setStyleSheet("font-size:22px; color:#00003b;")
        self.pushButton_8.setObjectName("pushButton_8")

        self.retranslateUi(Dialog)
        self.game.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Game", None, -1))
        self.pushButton_2.setText(QtWidgets.QApplication.translate("Dialog", "2", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("Dialog", "1", None, -1))
        self.lineEdit_2.setText(QtWidgets.QApplication.translate("Dialog", "__", None, -1))
        self.lineEdit.setText(QtWidgets.QApplication.translate("Dialog", "__", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Dialog", "Нажмите 1 или 2 чтобы играть!", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Dialog", "________________________", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("Dialog", "WIN: +750 $", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("Dialog", "lose: -250 $", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("Dialog", "______________________", None, -1))
        self.game.setTabText(self.game.indexOf(self.tab), QtWidgets.QApplication.translate("Dialog", "1 lvl ", None, -1))
        self.pushButton_3.setText(QtWidgets.QApplication.translate("Dialog", "1", None, -1))
        self.pushButton_4.setText(QtWidgets.QApplication.translate("Dialog", "2", None, -1))
        self.lineEdit_3.setText(QtWidgets.QApplication.translate("Dialog", "__", None, -1))
        self.lineEdit_4.setText(QtWidgets.QApplication.translate("Dialog", "__", None, -1))
        self.lineEdit_5.setText(QtWidgets.QApplication.translate("Dialog", "__", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("Dialog", "________________________", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("Dialog", "Нажмите 1 или 2 чтобы играть!", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("Dialog", "______________________", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("Dialog", "WIN: +1000 $", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("Dialog", "lose: -250 $", None, -1))
        self.game.setTabText(self.game.indexOf(self.tab_3), QtWidgets.QApplication.translate("Dialog", "2 lvl", None, -1))
        self.lineEdit_6.setText(QtWidgets.QApplication.translate("Dialog", "__", None, -1))
        self.lineEdit_7.setText(QtWidgets.QApplication.translate("Dialog", "__", None, -1))
        self.lineEdit_8.setText(QtWidgets.QApplication.translate("Dialog", "__", None, -1))
        self.pushButton_5.setText(QtWidgets.QApplication.translate("Dialog", "1", None, -1))
        self.pushButton_6.setText(QtWidgets.QApplication.translate("Dialog", "3", None, -1))
        self.pushButton_7.setText(QtWidgets.QApplication.translate("Dialog", "2", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("Dialog", "________________________", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("Dialog", "Нажмите 1, 2  или 3 чтобы играть!", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("Dialog", "________________________________", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("Dialog", "lose: -250 $", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("Dialog", "WIN: +2500 $", None, -1))
        self.game.setTabText(self.game.indexOf(self.tab_4), QtWidgets.QApplication.translate("Dialog", "3 lvl", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog", "Имя", None, -1))
        self.lineEdit_9.setText(QtWidgets.QApplication.translate("Dialog", "_____________________________", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog", "Накрутить счет", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog", "$", None, -1))
        self.pushButton_9.setText(QtWidgets.QApplication.translate("Dialog", "Применить", None, -1))
        self.pushButton_10.setText(QtWidgets.QApplication.translate("Dialog", "Применить", None, -1))
        self.game.setTabText(self.game.indexOf(self.tab_2), QtWidgets.QApplication.translate("Dialog", "Settings", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Dialog", "Счет = _________$", None, -1))
        self.pushButton_8.setText(QtWidgets.QApplication.translate("Dialog", "начать", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

